version: '3'

services:
  web:
    build: .
    volumes:
      - ./source:/app
    command: bash -c "if [ -z $PORT ]; then export PORT=8000; fi && gunicorn {{cookiecutter.app_name}}.app:app --bind 0.0.0.0:${PORT} --worker-class sanic.worker.GunicornWorker"
    
    ports:
      - ${PORT}:${PORT}
