version: '3'

services:
  web:
    build: .
    volumes:
      - ./source:/app
    command: bash -c "gunicorn {{cookiecutter.app_name}}.app:app --bind 0.0.0.0:8000 --worker-class sanic.worker.GunicornWorker"
    ports:
      - 8000:8000
